### ISSUE TITLE
lack of new features 

### ISSUE THREAD

**Issue by sarvl** [e841018/OfflineDesmos#1]
im not sure what exactly is missing but these are two examples that ive seen:
custom colors
![image](https://github.com/e841018/OfflineDesmos/assets/95301979/a9938fde-6688-417d-b247-6429d3476c4b)
loops on lists
![image](https://github.com/e841018/OfflineDesmos/assets/95301979/d5733a2c-6dfd-4432-abb1-56d31ec5999e)

**Comment by e841018** [comment]
The `calculator.js` is an old version (1.4), as you can see here:
https://github.com/e841018/OfflineDesmos/blob/dc23eda3658cb4f75365d9efbe0c7339395949ce/index.html#L7

You can update it to the newest version Desmos provides:
https://www.desmos.com/api/

**Comment by sarvl** [comment]
Ok thanks works perfectly
